//step 2 :Action Types
export const INPUT_CHANGE = "INPUT_CHANGE"
export const LOGIN ="LOGIN"
export const LOGIN_START ="LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN FAILED";
export const LOGIN_END ="LOGIN_END";
//register
export const REGISTER_START ="REGISTER_END"
export const REGISTER_SUCCESS ="REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_END ="REGISTER_END"
export const DEPARTMENT_CHECK_SUCCESS ="DEPARTMENT_CHECK_SUCCESS"
export const LOG_OUT = "LOG_OUT";
export const DEPARTMENT_CHECK ="DEPARTMENT_CHECK"
//fetch items
export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS ="GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL ="GET_ITEMS_FAIL";
export const GET_USER_ITEMS_START ="GET_USER_ITEMS_START"
export const GET_USER_ITEMS_SUCCESS ="GET_USERS_POST_SUCCESS"
export const GET_USER_ITEMS_FAILURE ="GET_USERS_ITEMS_FAILURE"

//post items
export const POST_ITEMS ="POST_ITEMS";
export const POST_ITEMS_SUCCESS ="POST_ITEMS_SUCCESS";
export const POST_ITEMS_FAILURE ="POST_ITEMS_FAILURE";

export const SUBMITTED_USER_DETAILS = "SUBMITTED_USER_DETAILS";
export const EDITED_USER_DETAILS = "EDITED_USER_DETAILS";
export const DELETED_USER_DETAILS = "DELETED_USER_DETAILS";
//owner
export const ADD_ITEM_START = "ADD_ITEM_START";
export const ADD_ITEM_SUCCESS ="ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE ="ADD_ITEMS_FAILURE"
export const DELETE_ITEM_START = "DELETE_ITEM_START";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE ="DELETE_ITEM_FAILURE"
//EDIT
export const EDIT_ITEM_START ="EDIT_ITEM_START";
export const EDIT_ITEM_SUCCESS= "EDIT_ITEM_SUCCESS"
export const UPDATE_ITEM_START= "UPDATE_ITEM_SUCESS"
export const UPDATE_ITEM_SUCCESS ="UPDAT_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE ="UPDATE_ITEM_FAILURE"