//step 2 :Action Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const SUBMITTED_USER_DETAILS = "SUBMITTED_USER_DETAILS";
export const DELETED_USER_DETAILS = "DELETED_USER_DETAILS";
export const GET_ITEMS = "GET_ITEMS"
export const CREATE_ITEMS = "CREATE_ITEMS ";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const TOKEN_CHECK_SUCCESS = "TOKEN_CHECK_SUCCESS";
export const TOKEN_CHECK_FAILURE = "TOKEN_CHECK_FAILURE";

